### ISSUE TITLE
Vm.DirEntry path string uses "\" symbol instead of "/"

### ISSUE THREAD

**Issue by pautib** [ChainAccelOrg/foundry-devops#25]
Hi everyone,

After following this section 
https://updraft.cyfrin.io/courses/foundry/foundry-fund-me/solidity-integration-tests
of the Foundry course, the call to the function
DevOpsTools.get_most_recent_deployment("FundMe", block.chainid);
was returning the following error to me:

```
[FAIL. Reason: setup failed: revert: No deployment artifacts were found for specified chain] setUp() (gas: 0)
```

I placed a console.log on the paths that were being retrieved on the get_most_recent_deployment function to check why my deployments were not being checked:
``` solidity

for (uint256 i = 0; i < entries.length; i++) {
            Vm.DirEntry memory entry = entries[i];
            console.log("Here: ", entry.path);
            if (
                entry.path.contains(string.concat("/", vm.toString(chainId), "/")) && entry.path.contains(".json")
                    && !entry.path.contains("dry-run")
            ) {

```

and it returned this:

```
Logs:
  The chain to use:  11155111
  Here:  C:/Users/jqd79530/Documents/Foundry/foundry-fund-me/broadcast\DeployFundMe.s.sol
  Here:  C:/Users/jqd79530/Documents/Foundry/foundry-fund-me/broadcast\DeployFundMe.s.sol\11155111
  Here:  C:/Users/jqd79530/Documents/Foundry/foundry-fund-me/broadcast\DeployFundMe.s.sol\11155111\run-1724018228.json
  Here:  C:/Users/jqd79530/Documents/Foundry/foundry-fund-me/broadcast\DeployFundMe.s.sol\11155111\run-1724101935.json
  Here:  C:/Users/jqd79530/Documents/Foundry/foundry-fund-me/broadcast\DeployFundMe.s.sol\11155111\run-latest.json
  Here:  C:/Users/jqd79530/Documents/Foundry/foundry-fund-me/broadcast\DeployFundMe.s.sol\31337
  Here:  C:/Users/jqd79530/Documents/Foundry/foundry-fund-me/broadcast\DeployFundMe.s.sol\31337\run-1724018316.json
  Here:  C:/Users/jqd79530/Documents/Foundry/foundry-fund-me/broadcast\DeployFundMe.s.sol\31337\run-1724018357.json
  Here:  C:/Users/jqd79530/Documents/Foundry/foundry-fund-me/broadcast\DeployFundMe.s.sol\31337\run-latest.json
```
After the **broadcast** folder, the path uses '\\' instead of '/'. To overcome this problem I just replaced the '/' with '\\' in the previous if statement to run my integration test. I would like to know if there is a better solution for this issue. I don't even know the root cause of it. Maybe it is because I am using Windows or because there is an error within this Vm.DirEntry struct.

This has been the  get_most_recent_deployment() function I used:

```solidity

    function get_most_recent_deployment(
        string memory contractName,
        uint256 chainId,
        string memory relativeBroadcastPath
    ) internal view returns (address) {
        address latestAddress = address(0);
        uint256 lastTimestamp;

        bool runProcessed;
        Vm.DirEntry[] memory entries = vm.readDir(relativeBroadcastPath, 3);
        for (uint256 i = 0; i < entries.length; i++) {
            Vm.DirEntry memory entry = entries[i];
            console.log("Here: ", entry.path);
            if (
                entry.path.contains(string.concat("\\", vm.toString(chainId), "\\")) && entry.path.contains(".json")
                    && !entry.path.contains("dry-run")
            ) {
                runProcessed = true;
                string memory json = vm.readFile(entry.path);

                uint256 timestamp = vm.parseJsonUint(json, ".timestamp");

                if (timestamp > lastTimestamp) {
                    latestAddress = processRun(json, contractName, latestAddress);

                    // If we have found some deployed contract, update the timestamp
                    // Otherwise, the earliest deployment may have been before `lastTimestamp` and we should not update
                    if (latestAddress != address(0)) {
                        lastTimestamp = timestamp;
                    }
                }
            }
        }

        if (!runProcessed) {
            revert("No deployment artifacts were found for specified chain");
        }

        if (latestAddress != address(0)) {
            return latestAddress;
        } else {
            revert("No contract deployed");
        }
    }

```
